# .github/workflows/child.yml
name: Child Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ inputs.name }}"
