# .github/workflows/trigger.yml
name: Trigger via Curl

on:
  push:
    branches: [main]

jobs:
  trigger-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger other workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"custom-trigger"}'
