# .github/workflows/workflow-dispatch-caller.yml
name: Workflow Dispatch Caller

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Another Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/target.yml/dispatches \
            -d '{"ref":"main"}'
